### ISSUE TITLE
Scale applied multiple times in getBoundingVolume Group

### ISSUE THREAD

**Issue by tthmok** [supereggbert/GLGE#15]
When using GLGE.Group.prototype.getBoundingVolume() the applyMatrixScale gets applied multiple times causing the end boundingVolume scale to be incorrect.

For instance a call to getBoundingVolume() on a regular Collada object that has a depth of 5 (this->child->child->child->child) yielded this bounding volume:
center: Array[3]
0: 0.06825499999999998
1: 0
2: 0.8567349999999996

dims: Array[3]
0: 0.43662999999999996
1: 6.64572
2: 5.8684899999999995

Then setting the Scale of that Collada object to 2x if you call getBoundingVolume() on that Collada object it can be scaled more than 2x.

Prop Scale 2x
center: Array[3]
0: 2.1841599999999994
1: 0
2: 27.415519999999987

dims: Array[3]
0: 13.972159999999999
1: 212.66304
2: 187.79167999999999

If we take dims[2] we can see exactly how much scaling was done.
5.8684899999999995 \* 2 \* 2 \* 2 \* 2 \* 2 = 187.79167999999999

**Comment by supereggbert** [comment]
Should be sorted now
