### ISSUE TITLE
Firefox error for too many parameters

### ISSUE THREAD

**Issue by franciscoreis** [supereggbert/GLGE#20]
Error: uncaught exception: [Exception... "Not enough arguments"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: http://localhost:8026/files/glge/glge-compiled.js :: <TOP_LEVEL> :: line 8988"  data: no]

8987 try{gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, canvas);}
8988 catch(e){gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE,canvas,null);}

Does not happen in Chrome.
Congratulations and thanks for version 0.8

**Comment by supereggbert** [comment]
Thanks franciscoreis, that's old code that should be safe to remove but if your seeing that error then the I would suspect there the canvas hasn't been created for some reason. Have you got an example some where, so I can try and recreate?

**Comment by franciscoreis** [comment]
As soon as I put a new version of my server on the cloud I will tell you how to recreate the error.  For now I'm working locally and using Chrome Canary build.

**Comment by supereggbert** [comment]
Assuming this is fixed now, shout if otherwise
