### ISSUE TITLE
Transparent materials aren't working anymore

### ISSUE THREAD

**Issue by martinruenz** [supereggbert/GLGE#30]
Hey,

I just realized, that this kind of transparent materials aren't working anymore:

```
<material id="B_transparent" specular="0" alpha="0.5">
   <texture id="b_tex" src="images/B_color.jpg"/>
   <material_layer texture="#b_tex" mapto="M_COLOR" mapinput="UV1"/>
</material>
```

Any ideas?

**Comment by supereggbert** [comment]
I think it's got something to do with the diffuse overriding alpha when it shouldn't be.  Should be a quick fix will be done in next couple of days.

**Comment by supereggbert** [comment]
Fixed now

**Comment by martinruenz** [comment]
Thanks!
