### ISSUE TITLE
Problem Windows GLGE

### ISSUE THREAD

**Issue by sofpower** [supereggbert/GLGE#32]
I’ve downloaded Minefield, Google Chrome 10 and others latest browsers, but the GLGE’s examples don’t work… The browser find webGL but the objects don’t appear in the scene. I don’t understand why… I only have this problem on Windows, it works on Mac OS…
If somebody can help me… It’s pretty urgent !

**Comment by henrikbennetsen** [comment]
Does any WebGL demo work? Try here:
http://khronos.org/webgl/wiki/Demo_Repository

If none of these work either then check this article:
http://ourbricks.zendesk.com/entries/381861-if-graphics-looks-wrong-or-browser-crashes
