### ISSUE TITLE
myObject.setPointSize() does not change anything

### ISSUE THREAD

**Issue by oal** [supereggbert/GLGE#39]
I'm trying to use point rendering, and, yes, the points are displayed. The problem is that they are 1px dots, and setting myObject.setPointSize(10), or any other number, does not change how it's displayed.

Here's how I try to use it:
  myObject = doc.getElement('box');
  myObject.setDrawType(GLGE.DRAW_POINTS);
  myObject.setPointSize(10);

Is this a bug in GLGE, or is there something here I have missed?

I used the most recent GLGE from Github.

**Comment by supereggbert** [comment]
What gfx card have you got? I think strictly speaking a es2.0 gfx card doesn't have to support any more then 1 pixel point(but I may be wrong). I think it might be a nice addition if GLGE was able to do some feature detection to allow user defined fall backs. I could also automatically fallback to rendering quads if the specified point size isn't supported but it might be a little while for that feature to show up. In the mean time you could have a look at the GLGE particle system to see if that might suit you needs.

**Comment by oal** [comment]
I've got a nVidia Geforce 8800GT, so it's not one of the newest cards around. That might be what's causing trouble.

More details about the card: http://www.nvidia.com/object/product_geforce_8800_gt_us.html
