### ISSUE TITLE
animations broken

### ISSUE THREAD

**Issue by mcbarnes** [supereggbert/GLGE#6]
Results from bisect:

279a130c77b8d9722a767808dac4bec10634e6fc is first bad commit
commit 279a130c77b8d9722a767808dac4bec10634e6fc
Author: Paul Brunt me@paulbrunt.co.uk
Date:   Mon May 3 11:45:05 2010 +0100

```
added soft shadows
```

:100755 100755 1923dc41d157ba386b1daaf817e8372feed2f53d c06e7996a4d7105954c0c4bd68fa3250b1a67f2b M  glge.js

**Comment by supereggbert** [comment]
I think it's all fixed now
