### ISSUE TITLE
Flicker when same material/texture used in many objects (with alpha?)

### ISSUE THREAD

**Issue by antont** [supereggbert/GLGE#62]
Apparently when there are many objects using the same material or texture, the texture display can flicker: sometimes the texture shows, sometimes drops to black, depending on the point of view.

This happens at least when the texture has alpha transparency.

A demo of the bug: http://www.realxtend.org/webnaali/flickerbug.html

I think I got it without alpha texture transparency too but that is unconfirmed, may try to make another test case about that. But would be great to get this fixed also when alpha transparency is used.

Oh: I got this with Chrome 16.0.912.77 on Linux (with nvidia proprietary drivers) but apparently it does not happen with Firefox 9.0.1 on the same machine

**Comment by antont** [comment]
Oh this looks quite similar and there's a fix too, "Chrome 16 and flickering faces with ThreeJS / WebGL" http://groups.google.com/group/webgl-dev-list/browse_thread/thread/8cabbc9f4c4cacde

**Comment by supereggbert** [comment]
This looks like a simple z-sorting issue. GLGE does it's best to sort objects to produce the best order. However, if you have multiple transparent objects all in the same place as in this case then there is nothing to say which is drawn first so it's sort is random resulting in flickering.  I've just added a new option to collada objects (setUseBinaryAlpha) if this is set to true then it will use binary alpha it won't look as smooth but it will fix all the flickering issues you're having.
