### ISSUE TITLE
Version 0.9 not found.

### ISSUE THREAD

**Issue by gKreator** [supereggbert/GLGE#63]
When I click the https://github.com/downloads/supereggbert/GLGE/GLGEv0.9.zip link it keeps saying that the file does not exist. I tried on a few different computers. All the other downloads work just fine.

**Comment by supereggbert** [comment]
Nice one, thanks a million,It was working earlier I've re-uploaded and it seems to be working again now...not sure why is fell over there :-(

**Comment by gKreator** [comment]
Ya I had to check like 20 times. It seemed un-natural. Also, did you get that email from like 3 days ago?

**Comment by supereggbert** [comment]
Hey GKrator,

Soz, I missed the email...please prompt if I miss you I do my best to keep up but things sometimes get the better of me.
