### ISSUE TITLE
WebGL readPixels() Spec Changes

### ISSUE THREAD

**Issue by eXLabT** [supereggbert/GLGE#9]
Using latest WebKit[Version 5.0 (6533.16, r61173)] or Chromium[6.0.433.0 (49597)] will face following 
error: "Uncaught TypeError: Cannot read property 'data' of undefined glge.js:4646". 
var data=gl.readPixels(0, 0, 4, 1, gl.RGBA, gl.UNSIGNED_BYTE);
 //TODO: firefox hack :-( remove when fixed!
if(data.data) data = data.data;
One solution could be:
"Compensating for WebGL readPixels() Spec Changes(http://asalga.wordpress.com/2010/07/14/compensating-for-webgl-readpixels-spec-changes/)"

**Comment by supereggbert** [comment]
Should be sorted now, everything seems to be working in the latest chromium and firefox
